version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emaildb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Веб-интерфейс MailHog

volumes:
  pgdata:
