version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emaildb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Веб-интерфейс
      - "1143:1143"  # IMAP без SSL
      - "1144:1144"  # IMAP с SSL
#
#  fastapi:
#    build:
#      context: .
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
#    env_file:
#      - .env.prod

volumes:
  pgdata: