"""Initial migration

Revision ID: 0641eaa290d6
Revises: 
Create Date: 2025-06-04 21:06:23.171390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0641eaa290d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
